### ISSUE TITLE
Failure to generate repo on Windows

### ISSUE THREAD

**Issue by kenzierocks** [IonicaBizau/github-contributions#43]
I tried to generate the repo, but the box popped up with this:
```
Error: Error: ENOENT, mkdir 'C:\Users\Kenzie Togami\AppData\Roaming\npm\node_modules\gh-contributions\lib\public\repos\hhv8llxnxh41jor'
```

**Comment by kenzierocks** [comment]
Looks like the `repos` directory was missing. This should probably be fixed.

**Comment by IonicaBizau** [comment]
So, is the issue fixed?

That's looks strange since [the `repos` directory is an empty one](https://github.com/IonicaBizau/github-contributions/tree/master/lib/public/repos).

I'm not running Windows on any machine, but only on some virtual environments. However, if anybody has a fix for this, contributions are welcome! :star2:

**Comment by kenzierocks** [comment]
I fixed it locally, by creating the `repos` dir, but I might PR a fix for everyone.

**Comment by IonicaBizau** [comment]
@kenzierocks Cool, but the [`repos`](https://github.com/IonicaBizau/github-contributions/tree/master/lib/public/repos) directory is already there.

**Comment by kenzierocks** [comment]
It's here on github, but it wasn't carried to my computer via NPM.

**Comment by IonicaBizau** [comment]
I have just tested it on Windows 7, virtual box, and it's working fine. I'm closing this for now. If there are other users reporting the same problem we will reopen it.
